### ISSUE TITLE
[ feature ] fetching data

### ISSUE THREAD

**Issue by 2-NOW** [codestates/beb-02-second-whiteam#28]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: client

### TODO
 1. [ ] fetching data using react-query
 2. [ ] use custom hooks

### USAGE
 1. [ ] explore - entire list
 2. [ ] mypage - filtered list
 3. [ ] community - posts
 4. [ ] post - comments
 5. [ ] login - OAuth
 6. [ ] buy/sell
 7. [ ] create collection

### Estimated time
>
