### ISSUE TITLE
[ feature ] buy/sell

### ISSUE THREAD

**Issue by 2-NOW** [codestates/beb-02-second-whiteam#30]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: client

### TODO
 1. [ ] buy ui - nft detail
 2. [ ] sell ui - mypage/collections/nft detail
 3. [ ] for sale view - explore

### Estimated time
> `3h`
